from datetime import datetime

SECTION_LABELS = {
    "summary":    "📄 Executive Summary",
    "legal":      "⚖️ Legal Review",
    "compliance": "🛡️ Compliance Check",
    "finance":    "📈 Financial Risk",
    "operations": "⚙️ Operations Review",
    "simplifier": "💬 Plain English Clauses",
    "risk":       "🚨 Risk Narrative",
}

def score_emoji(score: int) -> str:
    return "🟢" if score <= 3 else ("🟡" if score <= 6 else "🔴")

def score_label(score: int) -> str:
    if score <= 3:   return "Low Risk"
    elif score <= 5: return "Medium Risk"
    elif score <= 7: return "High Risk"
    return "Critical Risk"

def format_file_size(size_bytes: int) -> str:
    if size_bytes < 1024:           return f"{size_bytes} B"
    elif size_bytes < 1024 * 1024:  return f"{size_bytes/1024:.1f} KB"
    return f"{size_bytes/(1024*1024):.1f} MB"

def build_full_report(results: dict, filename: str) -> str:
    ts = datetime.now().strftime("%B %d, %Y at %H:%M")
    lines = [
        "# ClauseAI Contract Analysis Report", "",
        f"**Document:** {filename}  ", f"**Analysed:** {ts}  ",
        "**Platform:** ClauseAI Enterprise  ", "", "---", "",
    ]
    for key in ["summary","risk","legal","compliance","finance","operations","simplifier"]:
        if key in results and results[key]:
            label = SECTION_LABELS.get(key, key.title())
            content = results[key]
            if isinstance(content, dict):
                content = content.get("narrative", str(content))
            lines += [f"## {label}", "", str(content), "", "---", ""]
    lines.append("*Report generated by ClauseAI — Multi-Agent Contract Intelligence Platform*")
    return "\n".join(lines)

def build_plain_text_report(results: dict, filename: str) -> str:
    ts = datetime.now().strftime("%B %d, %Y at %H:%M")
    lines = [
        "CLAUSEAI CONTRACT ANALYSIS REPORT", "=" * 60,
        f"Document : {filename}", f"Analysed : {ts}",
        "Platform : ClauseAI Enterprise", "=" * 60, "",
    ]
    for key in ["summary","risk","legal","compliance","finance","operations","simplifier"]:
        if key in results and results[key]:
            label = SECTION_LABELS.get(key, key.title())
            clean = label.encode("ascii","ignore").decode().strip() or key.upper()
            content = results[key]
            if isinstance(content, dict):
                content = content.get("narrative", str(content))
            lines += [clean.upper(), "-" * len(clean), str(content), "", ""]
    lines.append("Report generated by ClauseAI — Multi-Agent Contract Intelligence Platform")
    return "\n".join(lines)